language: cpp
sudo: required
matrix:
  include:
    # Ubuntu14.04
    - os: linux
      dist: trusty
      compiler: gcc
    # Ubuntu12.04
    - os: linux
      compiler: gcc
    # Mac OSX
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
    - subversion

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install subversion; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
  - svn export http://svn.openrtm.org/OpenRTM-aist/trunk/OpenRTM-aist src

script:
    - ./analyze.sh --help
    - ./analyze.sh --cccc
    - ./analyze.sh --sloccount
    - ./analyze.sh --cpd
    - ./analyze.sh --cpplint
    - ./analyze.sh --cppcheck
    - ./analyze.sh --all
